"""cria tabelas iniciais

Revision ID: 3e9ed9bb9055
Revises: 
Create Date: 2026-09-14 10:45:09.968605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9ed9bb9055'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('cardapio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo_refeicao', sa.Enum('CAFE_DA_MANHA', 'ALMOCO', 'JANTAR', name='tipo_refeicao'), nullable=False),
    sa.Column('fonte_pdf_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'data', 'tipo_refeicao', name='uq_cardapio_campus_data_tipo')
    )
    op.create_table('checkin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardapio_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('nota >= 1 AND nota <= 5', name='ck_avaliacao_nota_range'),
    sa.ForeignKeyConstraint(['cardapio_id'], ['cardapio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_cardapio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardapio_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Enum('BEBIDA', 'PANIFICACAO', 'OPCAO_EXTRA', 'GORDURA', 'SALADA_1', 'SALADA_2', 'MOLHO_SALADA', 'PRATO_PRINCIPAL', 'GUARNICAO', 'SOPA', 'TORRADA', 'ACOMPANHAMENTO', 'SOBREMESA', 'FRUTA', name='categoria'), nullable=False),
    sa.Column('tipo_dieta', sa.Enum('COMUM', 'PADRAO', 'OVOLACTOVEGETARIANO', 'VEGETARIANO_ESTRITO', name='tipo_dieta'), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('contem_leite', sa.Boolean(), nullable=False),
    sa.Column('contem_ovo', sa.Boolean(), nullable=False),
    sa.Column('contem_gluten', sa.Boolean(), nullable=False),
    sa.Column('contem_cogumelo', sa.Boolean(), nullable=False),
    sa.Column('contem_mel', sa.Boolean(), nullable=False),
    sa.Column('contem_soja', sa.Boolean(), nullable=False),
    sa.Column('contem_pimenta', sa.Boolean(), nullable=False),
    sa.Column('contem_oleaginosas', sa.Boolean(), nullable=False),
    sa.Column('contem_carne_suina', sa.Boolean(), nullable=False),
    sa.Column('contem_frutos_do_mar', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cardapio_id'], ['cardapio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_cardapio')
    op.drop_table('avaliacao')
    op.drop_table('checkin')
    op.drop_table('cardapio')
    op.drop_table('campus')
    # ### end Alembic commands ###
